# Generated by Django 6.1 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_anti_cheat_enabled_quiz_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='class_name',
            field=models.CharField(
                blank=True,
                help_text='Leave blank to make this quiz available to all students.',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='section',
            field=models.CharField(
                blank=True,
                help_text='Optional section filter when class_name is set.',
                max_length=50,
                null=True,
            ),
        ),
    ]
